interface=wlan0
driver=nl80211

ssid=Olympus-Rover
hw_mode=g
channel=6
ieee80211n=1
wmm_enabled=1

# Seguridad WPA2
auth_algs=1
wpa=2
wpa_passphrase=olympus2026
wpa_key_mgmt=WPA-PSK
rsn_pairwise=CCMP

# Sin filtrado MAC — cualquier laptop del equipo puede conectar
macaddr_acl=0
ignore_broadcast_ssid=0
